version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=database
    networks:
      - pucapp_network
    ports:
      - "5432:5432"
    volumes:
      - ./database/postgres_data:/var/lib/postgres
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8081:80"
    user: "5050:5050"
    networks:
      - pucapp_network

volumes:
  postgres_data:

networks:
  pucapp_network:
    driver: bridge